### ISSUE TITLE
aliases do not work in built bot

### ISSUE THREAD

**Issue by paperdave** [CRBT-Team/Purplet#10]
we might not consider config.alias during build but if we do it doesn't work as of purplet-next.11 iirc

**Comment by davecaruso** [comment]
I'm adding high priority to this since you can't run the example in production with this.

**Comment by paperdave** [comment]
in `packages/purplet/cli/build.ts`

`config.alias` has to be handled.

`packages/purplet/src/config/vite.ts` contains how i use it for dev, which i believe vite passes this to rollup plugin alias if im not mistaken. kinda copy paste from here. could abstract this logic to a shared function as well.
