### ISSUE TITLE
Setup ESLint

### ISSUE THREAD

**Issue by paperdave** [CRBT-Team/Purplet#18]
eslint is setup, however we do not use it due to https://github.com/davecaruso/various-web/issues/1, which is from my personal eslint config. i never set it up to use typescript properly so we get a lot of lint errors when it comes to it.

once that closes i'll setup eslint project wide

**Comment by Hycord** [comment]
could we use a popular eslint config like airbnb, or just create a new eslint config from scratch specifically for this project, and get it fully, 100% fleshed out to the point that literally any project using eslint could use it and it wouldn't cause a bunch of stupid errors?

**Comment by paperdave** [comment]
BTW, im waiting for a few of my branches to merge before I fully enable this (and fix every lint issue without merge conflicts) but it's on my radar.
