### ISSUE TITLE
Opcode 9 "Invalid Session" is not properly implemented.

### ISSUE THREAD

**Issue by paperdave** [CRBT-Team/Purplet#42]
- https://discord.com/developers/docs/topics/gateway#invalid-session

Currently we just reconnect on this, but we are only supposed to do so if it's a resumable connection. We also need to handle if this happens before a ready event, in that case it means we have a bad session/token, or something.

**Comment by davecaruso** [comment]
in relation, tricked was getting gateway sesion invalidated loops so that might be to be investigated if i can reproduce that

![image](https://user-images.githubusercontent.com/24465214/178434854-006dce2e-c767-42a9-a389-690976d43e22.png)
