### ISSUE TITLE
Purplet depends on `@discordjs/rest`'s `cdn` object which we didn't implement

### ISSUE THREAD

**Issue by paperdave** [CRBT-Team/Purplet#51]
We didn't implement this feature because it's not rest related, it's just url generating. We can create some utilities at some point. Will probably be closed during dev of purplet structures

**Comment by Hycord** [comment]
Feels like something that should be put into buncord

**Comment by paperdave** [comment]
@Clembs this would likely go into `@purplet/structures` directly when needed, or maybe do you think having a separate set of url formatter functions like `getEmojiURL(emojiId, imageOpts)` in a package like `@purplet/utils` (a package i've already wanted to make for some discord-specific utility functions we have).

all i know is the rest client seems like the wrong place for this logic since it's not the usual thing to be `fetch`ing these resources, and even if that was the case, they are not json results (obviously) and other implications.

**Comment by Clembs** [comment]
I'm 100% on board with coding a `@purplet/utils` package, which I also thought of a while back.

**Comment by Clembs** [comment]
closed with commit [ce4f3fe](https://github.com/CRBT-Team/Purplet/commit/ce4f3fe166d661ff180b35008f49cfe208ec3640)
