### ISSUE TITLE
Support running with bun

### ISSUE THREAD

**Issue by paperdave** [CRBT-Team/Purplet#6]
bun is a new runtime, package manager, transpiler, and bundler- all in one. still experimental, but I believe it is the future as it's current benchmarks crush node.

some people in the bun discord were thinking about was some bun version of discord.js (I heard buncord as a name being thrown around), but i believe the best approach would be to make something that would work in both node AND bun, as bun just implements web standards like WebSocket and fetch, so we would just have to polyfill these types of things with the npm packages we use currently. then we would also have to take a look at replacing packages that do not run in bun, but jarred is constantly making things work so we also have the option to wait.

this issue can be two things
- the creation of a separate package that acts as a discord api library instead of a full framework
- making the framework as a whole run in bun (and node)

## list of packages that we depend on that do not work in bun

I tested this on July 7th:

- `@discordjs/rest`, but I plan to ship my own rest client
- `yargs`, has a `process.version` check. since I overwrite our cli formatting I think it would be best we ship our own arg parser or switch to another one. I don't know any other arg parsers so I would love any suggestions.
- `chalk`, due to a not implemented feature in bun with package json imports field
- `ora` as it depends on chalk
- `fast-equals` due to a bug in bun loading esm files but in cjs mode breaking.
- `vite` and `rollup`, but our usage of this is for the framework which I think would be better to use Bun's transpiler and bundle API, but this means we'd have to maintain multiple versions of the dev and build process. I have a feeling that we might just see a bun-accelerated polyfill for these packages later on.
- `prompts`, I don't know why it just fails at runtime
- `chokidar`, it works but never emits events when I tried it.

I'm going to post some issues relating to splitting packages off, and if any of those happen they should have this issue in mind when they do so.

**Comment by davecaruso** [comment]
I just implemented GatewayClient in a way that would work on bun but we are stuck waiting on this issue. I have a workaround, but it should be fixed upstream. https://github.com/Jarred-Sumner/bun/issues/521

**Comment by paperclover** [comment]
this issue wont be needed as i bun will eventually support all of these and maybe they already do that.
