### ISSUE TITLE
gateway: doesn't handle all ws close codes 

### ISSUE THREAD

**Issue by paperdave** [CRBT-Team/Purplet#67]
original message:

idk, i just left it open and i get, in `purplet@2.0.0-next.18`, an `Error: not opened`, meaning the ws closed.

core issue:

we don't implement a handler for close code 1006, and we should be handling the rest of them

**Comment by pharuxtan** [comment]
This surely happened because your internet was disconnect for a couple of seconds which caused the WebSocket closing with the code 1006 (Abnormal closure), if you want a list of WebSocket close code standards, here there are: https://www.rfc-editor.org/rfc/rfc6455.html#section-7.4.1

**Comment by paperdave** [comment]
must have been. I don't handle any of the close codes outside 4xxx ones that discord defines. ideally each code should be handled not just the abnormal closure one.
