### ISSUE TITLE
Our own rest client

### ISSUE THREAD

**Issue by davecaruso** [CRBT-Team/Purplet#7]
working with `@discordjs/rest` is less than ideal, and glancing at it's code makes me feel like it's overcomplicated. I would like to have our own rest client, simply a set of functions that wrap fetch, implement rate limiting, errors, and (most important) provide typedefs for each known API route, because discord.js' doesn't do this for some reason.

if anyone wants to take this task up, I think a good name would be `@purplet/rest` (then a future `@purplet/gateway`), but the exact API I'm unsure of, maybe something like `rest.resourceName.actionName()` where these just mirror the discord api docs, such as `rest.channel.createMessage({ opts })` but also `rest.methodName(url, opts)`

**Comment by Clembs** [comment]
oh hell yeah

**Comment by Hycord** [comment]
I'm down to work on this.
I personally like the `rest.resouceName.actionName()` best, but let me know what everyone here wants to do

**Comment by davecaruso** [comment]
> I'm down to work on this. I personally like the `rest.resouceName.actionName()` best, but let me know what everyone here wants to do

you can start by copying the file structure of `packages/serialize` as that includes the basic compilation workflow, edit it to be `@purplet/rest`. afterwards you can create a folder prefixed with `local` anywhere in the monorepo and run `pnpm install @purplet/rest`, and it should resolve properly.
